# Artficial neural networks

# 1.EDA and Preprocessing

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/Alphabets_data.csv')
df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [5]:
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [7]:
#checking for missing value
missing_values = df.isnull().sum()

In [9]:
#check for duplicates
df.duplicated().sum()

np.int64(1332)

In [11]:
#remove duplicate data
data = df.drop_duplicates()

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data['letter'].unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

In [14]:
from sklearn.preprocessing import MinMaxScaler

x = data.drop(columns=['letter'])
y = data['letter']

#mimax scaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [15]:
from sklearn.preprocessing import OneHotEncoder

# One-hot encode the target variable
encoder = OneHotEncoder()
y_en = encoder.fit_transform(y.values.reshape(-1, 1))
y_encoded = pd.DataFrame(y_en.toarray())

In [16]:
y_encoded

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18664,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18665,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18667,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Model implimentation

In [18]:
from sklearn.model_selection import train_test_split

# split into train and test
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
model1 = Sequential([
    Dense(12, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='softmax')
])

# since its a multiclass classification problem so im using relu for hidden layer and softmax for output layer

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
#I'm using adam optimizer bcz it uses both adagrad and rmsprop properties

In [22]:
training = model1.fit(x_train, y_encoded, epochs=20, batch_size=20, validation_split=0.2)

Epoch 1/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0378 - loss: 3.2672 - val_accuracy: 0.0422 - val_loss: 3.2566
Epoch 2/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0431 - loss: 3.2572 - val_accuracy: 0.0388 - val_loss: 3.2562
Epoch 3/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0446 - loss: 3.2559 - val_accuracy: 0.0395 - val_loss: 3.2565
Epoch 4/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0392 - loss: 3.2565 - val_accuracy: 0.0382 - val_loss: 3.2568
Epoch 5/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0442 - loss: 3.2560 - val_accuracy: 0.0405 - val_loss: 3.2567
Epoch 6/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0467 - loss: 3.2549 - val_accuracy: 0.0405 - val_loss: 3.2567
Epoch 7/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0424 - loss: 3.2551 - val_accuracy: 0.0449 - val_loss: 3.2568
Epoch 8/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0483 - loss: 3.2545 - val_accuracy: 0.0392 - val_loss: 3.2558
Epoch 9/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0423 - loss: 3.2552 - val_accuracy: 0.0382 - val_loss: 3.2563
Epoch 10/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0427 - loss: 3.2541 - val_accuracy: 0.0355 - val_loss: 3.2556
Epoch 11/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0489 - loss: 3.2541 - val_accuracy: 0.0425 - val_loss: 3.2560
Epoch 12/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0433 - loss: 3.2535 - val_accuracy: 0.0385 - val_loss: 3.2557
Epoch 13/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0435 - loss: 3.2538 - val_accuracy: 0.0352 - val_loss: 3.2558
Epoch 14/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0444 - loss: 3.2530 - val_accuracy: 0.0412 - val_loss: 3.2563
Epoch 15/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0470 - loss: 3.2531 - val_accuracy: 0.0355 - val_loss: 3.2557
Epoch 16/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0446 - loss: 3.2535 - val_accuracy: 0.0375 - val_loss: 3.2558
Epoch 17/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0479 - loss: 3.2521 - val_accuracy: 0.0382 - val_loss: 3.2558
Epoch 18/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0510 - loss: 3.2512 - val_accuracy: 0.0388 - val_loss: 3.2559
Epoch 19/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0487 - loss: 3.2517 - val_accuracy: 0.0385 - val_loss: 3.2567
Epoch 20/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0508 - loss: 3.2500 - val_accuracy: 0.0368 - val_loss: 3.2558

# 3.Hyperparameter tuning

In [23]:
model2 = Sequential([
    Dense(56, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model2.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model2.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0441 - loss: 3.2645 - val_accuracy: 0.0355 - val_loss: 3.2602
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0431 - loss: 3.2573 - val_accuracy: 0.0335 - val_loss: 3.2601
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0407 - loss: 3.2562 - val_accuracy: 0.0348 - val_loss: 3.2613
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0439 - loss: 3.2541 - val_accuracy: 0.0372 - val_loss: 3.2608
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0449 - loss: 3.2551 - val_accuracy: 0.0388 - val_loss: 3.2596
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0456 - loss: 3.2534 - val_accuracy: 0.0378 - val_loss: 3.2602
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0515 - loss: 3.2502 - val_accuracy: 0.0375 - val_loss: 3.2591
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0512 - loss: 3.2498 - val_accuracy: 0.0395 - val_loss: 3.2606
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0505 - loss: 3.2496 - val_accuracy: 0.0358 - val_loss: 3.2599
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0472 - loss: 3.2503 - val_accuracy: 0.0398 - val_loss: 3.2601
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0455 - loss: 3.2498 - val_accuracy: 0.0405 - val_loss: 3.2605
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0503 - loss: 3.2490 - val_accuracy: 0.0355 - val_loss: 3.2604
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0503 - loss: 3.2466 - val_accuracy: 0.0352 - val_loss: 3.2629
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0495 - loss: 3.2478 - val_accuracy: 0.0415 - val_loss: 3.2620
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0505 - loss: 3.2475 - val_accuracy: 0.0395 - val_loss: 3.2613
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0516 - loss: 3.2466 - val_accuracy: 0.0392 - val_loss: 3.2619
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0524 - loss: 3.2450 - val_accuracy: 0.0365 - val_loss: 3.2613
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0499 - loss: 3.2432 - val_accuracy: 0.0385 - val_loss: 3.2608
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0520 - loss: 3.2423 - val_accuracy: 0.0345 - val_loss: 3.2611
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0538 - loss: 3.2424 - val_accuracy: 0.0362 - val_loss: 3.2633

In [24]:
model3 = Sequential([
    Dense(56, activation='elu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model3.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model3.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0351 - loss: 3.2840 - val_accuracy: 0.0429 - val_loss: 3.2631
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0437 - loss: 3.2609 - val_accuracy: 0.0439 - val_loss: 3.2598
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0406 - loss: 3.2582 - val_accuracy: 0.0402 - val_loss: 3.2590
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0429 - loss: 3.2579 - val_accuracy: 0.0412 - val_loss: 3.2622
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0422 - loss: 3.2570 - val_accuracy: 0.0392 - val_loss: 3.2604
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0424 - loss: 3.2548 - val_accuracy: 0.0412 - val_loss: 3.2620
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0447 - loss: 3.2523 - val_accuracy: 0.0378 - val_loss: 3.2624
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0476 - loss: 3.2507 - val_accuracy: 0.0398 - val_loss: 3.2623
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0458 - loss: 3.2520 - val_accuracy: 0.0408 - val_loss: 3.2613
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0464 - loss: 3.2516 - val_accuracy: 0.0398 - val_loss: 3.2614
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0486 - loss: 3.2514 - val_accuracy: 0.0408 - val_loss: 3.2648
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0516 - loss: 3.2509 - val_accuracy: 0.0408 - val_loss: 3.2626
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0490 - loss: 3.2502 - val_accuracy: 0.0408 - val_loss: 3.2625
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0544 - loss: 3.2469 - val_accuracy: 0.0402 - val_loss: 3.2639
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0503 - loss: 3.2500 - val_accuracy: 0.0398 - val_loss: 3.2624
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0497 - loss: 3.2467 - val_accuracy: 0.0385 - val_loss: 3.2661
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0465 - loss: 3.2485 - val_accuracy: 0.0415 - val_loss: 3.2657
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0492 - loss: 3.2461 - val_accuracy: 0.0388 - val_loss: 3.2650
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0475 - loss: 3.2484 - val_accuracy: 0.0385 - val_loss: 3.2652
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0482 - loss: 3.2488 - val_accuracy: 0.0395 - val_loss: 3.2657

In [25]:
model4 = Sequential([
    Dense(56, activation='tanh', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model4.compile(optimizer='ADAgrad', loss='categorical_crossentropy', metrics=['accuracy'])
training = model4.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0401 - loss: 3.2915 - val_accuracy: 0.0382 - val_loss: 3.2717
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0362 - loss: 3.2774 - val_accuracy: 0.0395 - val_loss: 3.2659
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0353 - loss: 3.2728 - val_accuracy: 0.0378 - val_loss: 3.2630
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0370 - loss: 3.2663 - val_accuracy: 0.0405 - val_loss: 3.2614
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0354 - loss: 3.2656 - val_accuracy: 0.0392 - val_loss: 3.2605
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0400 - loss: 3.2621 - val_accuracy: 0.0388 - val_loss: 3.2599
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: 3.2628 - val_accuracy: 0.0395 - val_loss: 3.2595
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0405 - loss: 3.2615 - val_accuracy: 0.0395 - val_loss: 3.2592
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0379 - loss: 3.2632 - val_accuracy: 0.0405 - val_loss: 3.2591
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0353 - loss: 3.2609 - val_accuracy: 0.0415 - val_loss: 3.2589
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0370 - loss: 3.2621 - val_accuracy: 0.0422 - val_loss: 3.2588
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0348 - loss: 3.2623 - val_accuracy: 0.0402 - val_loss: 3.2588
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0359 - loss: 3.2625 - val_accuracy: 0.0408 - val_loss: 3.2587
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0332 - loss: 3.2607 - val_accuracy: 0.0408 - val_loss: 3.2587
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0353 - loss: 3.2608 - val_accuracy: 0.0402 - val_loss: 3.2586
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0357 - loss: 3.2613 - val_accuracy: 0.0398 - val_loss: 3.2586
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0367 - loss: 3.2584 - val_accuracy: 0.0392 - val_loss: 3.2586
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0368 - loss: 3.2600 - val_accuracy: 0.0402 - val_loss: 3.2586
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0395 - loss: 3.2606 - val_accuracy: 0.0412 - val_loss: 3.2586
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0386 - loss: 3.2573 - val_accuracy: 0.0408 - val_loss: 3.2586

# 4.Evaluation

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np
# Get the true labels
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model1.predict(x_test), axis=1)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

print("Model with relu , softmax and adam optimizer ")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Model with relu , softmax and adam optimizer
Accuracy: 0.05195500803427959
Precision: 0.013414457041225285
Recall: 0.05195500803427959
F1-score: 0.016214436195583548

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [27]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model2.predict(x_test), axis=1)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

print("Model with relu , sigmoid and RMSprop")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Model with relu , sigmoid and RMSprop
Accuracy: 0.08248527048741296
Precision: 0.06306690226603068
Recall: 0.08248527048741296
F1-score: 0.054616790740143716

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [28]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model3.predict(x_test), axis=1)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

print("Model with elu,sigmoid and RMSprop")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Model with elu,sigmoid and RMSprop
Accuracy: 0.0693626138189609
Precision: 0.04069137219802483
Recall: 0.0693626138189609
F1-score: 0.03990103194219987

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [29]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model4.predict(x_test), axis=1)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

print("Model with tanh and Adgrad ")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Model with tanh and Adgrad
Accuracy: 0.028387787895018748
Precision: 0.017762679434682987
Recall: 0.028387787895018748
F1-score: 0.01921115721591181

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))